logLevel: "debug"
usbMountFolder: "/mnt/usbfs"
archiveFolder: "/cache"
processDelayMinutes: 5 # only process clips older than x minutes
filesystemFileUploader:
  path: "/mnt/nfs"
  requiresMount: true